theme: jekyll-theme-leap-day
title: Code 201 - Fundamentals.
description: Fundamentos del Desarrollo de Software.
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  parse_block_html: true